"use strict";
window.ISSUE_GUIDE = {
  "version": 1,
  "asOfDate": "2026-10-09",
  "questions": [
    {
      "id": "q_palestinian_state",
      "topicId": "security_foreign_relations",
      "titleHe": "הסדר מדיני עם הפלסטינים",
      "promptHe": "מה מתועד על הצעות להסדר מדיני ועל שאלת המדינה הפלסטינית?",
      "explanationHe": "אין להסיק עמדה על הסדר קבע מתכנית ביטחונית כללית.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_gaza_day_after",
      "topicId": "security_foreign_relations",
      "titleHe": "ניהול אזרחי ברצועת עזה",
      "promptHe": "מה מתועד על האחריות לניהול העניינים האזרחיים ברצועת עזה?",
      "explanationHe": "יש להפריד בין ניהול אזרחי לבין חופש פעולה צבאי. פרסום הצעה אינו תיאור של המצב כיום.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [
          "e_beyachad_gaza"
        ],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [
          "e_yisrael_beitenu_gaza"
        ],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_settlements",
      "topicId": "security_foreign_relations",
      "titleHe": "מדיניות ההתיישבות",
      "promptHe": "מה מתועד על פיתוח יישובים ועל מדיניות ההתיישבות?",
      "explanationHe": "הייחוס הגאוגרפי חשוב: פיתוח אזורי גבול אינו בהכרח הצעה לגבי יהודה ושומרון.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [
          "e_likud_settlements"
        ],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [
          "e_joint_list_spending"
        ],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [
          "e_amcha_israel_border_settlements"
        ],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_death_penalty",
      "topicId": "security_foreign_relations",
      "titleHe": "עונש מוות בעבירות טרור",
      "promptHe": "מה מתועד על הצעות ומדיניות בענישה בעבירות טרור?",
      "explanationHe": "הנושא אינו קובע אם חוק כלשהו עבר או מהו הדין הקיים; לשם כך נדרשת רשומת חקיקה.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_free_market",
      "topicId": "economy_cost_of_living",
      "titleHe": "תחרות ורגולציה",
      "promptHe": "מה מתועד על תחרות, ריכוזיות והסדרת השוק?",
      "explanationHe": "יש להבחין בין עיקרון כללי, כלי מדיניות מוצע ורפורמה שבוצעה.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [
          "e_beyachad_competition"
        ],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [
          "e_likud_market"
        ],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [
          "e_haredi_public_market"
        ],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [
          "e_yashar_competition"
        ],
        "yisrael_beitenu": [
          "e_yisrael_beitenu_competition"
        ],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_housing_prices",
      "topicId": "economy_cost_of_living",
      "titleHe": "נגישות לדיור",
      "promptHe": "מה מתועד על הצעות להרחבת היצע הדיור ולסיוע בשכירות או ברכישה?",
      "explanationHe": "יעדי בנייה וסבסוד הם הבטחות, לא דירות שנבנו או הוזלה שהוכחה.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [
          "e_beyachad_housing"
        ],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [
          "e_likud_housing"
        ],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [
          "e_haredi_public_housing"
        ],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [
          "e_joint_list_housing"
        ],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_welfare_allowances",
      "topicId": "economy_cost_of_living",
      "titleHe": "קצבאות וסיוע כלכלי",
      "promptHe": "מה מתועד על היקף הסיוע הכלכלי ועל תנאי הזכאות לו?",
      "explanationHe": "תכנית ממוקדת בקבוצה מסוימת אינה עמדה על כל מערך הקצבאות.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [
          "e_beyachad_benefits"
        ],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [
          "e_yisrael_beitenu_pensions"
        ],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_minimum_wage_workers",
      "topicId": "economy_cost_of_living",
      "titleHe": "שכר מינימום",
      "promptHe": "מה מתועד על גובה שכר המינימום ועל אופן קביעתו?",
      "explanationHe": "הצעה להעלאת שכר שונה מהבטחה לאכוף את הדין הקיים.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [
          "e_joint_list_minimum_wage"
        ],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_judicial_reform",
      "topicId": "institutions_democracy",
      "titleHe": "מעמד מערכת המשפט",
      "promptHe": "מה מתועד על עצמאות מערכת המשפט ועל סמכויותיה?",
      "explanationHe": "יש לקרוא את הכלים המוצעים עצמם, ולא להסתפק בתווית בעד או נגד רפורמה.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [
          "e_yashar_judiciary"
        ],
        "yisrael_beitenu": [],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [
          "e_noam_override"
        ],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_state_inquiry",
      "topicId": "institutions_democracy",
      "titleHe": "חקירת אירועי שבעה באוקטובר",
      "promptHe": "מה מתועד על היקף החקירה ועל המתכונת המוצעת לה?",
      "explanationHe": "קריאה לחקירה אינה בהכרח הצעה לוועדת חקירה ממלכתית; הסיכום מציין את המתכונת שנכתבה.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [
          "e_beyachad_inquiry"
        ],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [
          "e_miluimnikim_economic_inquiry"
        ],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [
          "e_yashar_inquiry"
        ],
        "yisrael_beitenu": [
          "e_yisrael_beitenu_inquiry"
        ],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_term_limits",
      "topicId": "institutions_democracy",
      "titleHe": "הגבלת כהונת ראש הממשלה",
      "promptHe": "מה מתועד על הגבלת משך כהונת ראש הממשלה?",
      "explanationHe": "אין להוסיף מספר שנים או קדנציות אם הוא לא נתמך בקטע שנבדק.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [
          "e_yashar_term_limits"
        ],
        "yisrael_beitenu": [
          "e_yisrael_beitenu_term_limits"
        ],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_arab_integration",
      "topicId": "institutions_democracy",
      "titleHe": "מדיניות כלפי החברה הערבית",
      "promptHe": "מה מתועד על תכניות המופנות לחברה הערבית?",
      "explanationHe": "יש להבחין בין תכנית שירותים ותשתיות לבין תכנית אכיפה; כל קטע מיוחס למטרתו.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [
          "e_joint_list_arab_development"
        ],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [
          "e_yashar_police"
        ],
        "yisrael_beitenu": [],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_civil_marriage",
      "topicId": "religion_state",
      "titleHe": "הסדרת זוגיות אזרחית",
      "promptHe": "מה מתועד על מסלולים אזרחיים להסדרת זוגיות?",
      "explanationHe": "ברית זוגיות ונישואים אזרחיים אינם אותו ניסוח. המאגר אינו מחליף אותם זה בזה.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [
          "e_beyachad_civil_union"
        ],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [
          "e_yisrael_beitenu_marriage"
        ],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_conversion_reform",
      "topicId": "religion_state",
      "titleHe": "מדיניות הגיור",
      "promptHe": "מה מתועד על סמכויות גיור ועל המסלולים המוצעים?",
      "explanationHe": "ביזור גיור אורתודוקסי אינו כשלעצמו תיעוד להכרה בגיור של זרמים אחרים.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [
          "e_beyachad_conversion"
        ],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [
          "e_yisrael_beitenu_conversion"
        ],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_kashrut_religious_services",
      "topicId": "religion_state",
      "titleHe": "הסדרת הכשרות",
      "promptHe": "מה מתועד על הכרה בכשרות ועל הגופים המספקים אותה?",
      "explanationHe": "יש לבדוק איזה שינוי הוצע, בלי להסיק ביטול של כלל שירותי הדת.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [
          "e_beyachad_kashrut"
        ],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_lgbtq_rights",
      "topicId": "religion_state",
      "titleHe": "זכויות להט״ב",
      "promptHe": "מה מתועד על הצעות הנוגעות לזכויות להט״ב?",
      "explanationHe": "עמדה על הכרה בזוגיות אינה לבדה תיעוד לכל הצעת שוויון אחרת.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [
          "e_beyachad_lgbtq"
        ],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_haredi_conscription",
      "topicId": "public_services_equality",
      "titleHe": "שירות בציבור החרדי",
      "promptHe": "מה מתועד על חובת שירות ועל מסלולים לציבור החרדי?",
      "explanationHe": "יש לקרוא גם חריגים, מסלולים מותאמים וסנקציות שנכתבו, בלי להמציא פטור או חובה שלא פורטו.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [
          "e_miluimnikim_economic_service"
        ],
        "pirates": [],
        "haredi_public": [
          "e_haredi_public_service"
        ],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [
          "e_yashar_service"
        ],
        "yisrael_beitenu": [
          "e_yisrael_beitenu_service"
        ],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [
          "e_amcha_israel_service"
        ],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_core_curriculum",
      "topicId": "public_services_equality",
      "titleHe": "לימודי ליבה ומימון חינוך",
      "promptHe": "מה מתועד על תכני ליבה ועל הקשר שלהם למימון מוסדות חינוך?",
      "explanationHe": "תמיכה באנגלית ומתמטיקה אינה בהכרח התניית כל התקציב בליבה מלאה.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [
          "e_beyachad_core"
        ],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [
          "e_haredi_public_education"
        ],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [
          "e_yashar_core"
        ],
        "yisrael_beitenu": [
          "e_yisrael_beitenu_core"
        ],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_healthcare_periphery",
      "topicId": "public_services_equality",
      "titleHe": "נגישות לשירותי בריאות",
      "promptHe": "מה מתועד על הצעות לשיפור נגישות לשירותי בריאות?",
      "explanationHe": "יש להפריד בין הבטחת השקעה לבין תיעוד של שירותים שכבר נוספו.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [
          "e_beyachad_health"
        ],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [
          "e_likud_health"
        ],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [
          "e_yashar_health"
        ],
        "yisrael_beitenu": [],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_nation_state_law",
      "topicId": "public_services_equality",
      "titleHe": "חוק הלאום ועיגון שוויון",
      "promptHe": "מה מתועד על הצעות הנוגעות לחוק הלאום ולעיגון שוויון?",
      "explanationHe": "הצהרה כללית על שוויון אינה ראיה להצעה לשנות חוק מסוים.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_shabbat_transport",
      "topicId": "environment_infrastructure",
      "titleHe": "תחבורה ציבורית בשבת",
      "promptHe": "מה מתועד על הסדרים להפעלת תחבורה ציבורית בשבת?",
      "explanationHe": "אין להסיק עמדה על תחבורה משמירת שבת כללית או מתכנית תחבורה בימי חול.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [
          "e_beyachad_shabbat_transport"
        ],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [
          "e_yisrael_beitenu_shabbat_transport"
        ],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_renewable_energy_climate",
      "topicId": "environment_infrastructure",
      "titleHe": "היערכות לאקלים והפחתת פליטות",
      "promptHe": "מה מתועד על תכניות אקלים ועל יעדים להפחתת פליטות?",
      "explanationHe": "הבטחה לחוק אקלים אינה ראיה לחוק קיים או לעמידה ביעד.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [
          "e_beyachad_climate"
        ],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_public_transit_congestion",
      "topicId": "environment_infrastructure",
      "titleHe": "תחבורה ציבורית וגודש",
      "promptHe": "מה מתועד על פיתוח תחבורה ציבורית ועל ניהולה?",
      "explanationHe": "אזכור כללי של תשתיות אינו ראיה לתכנית רכבת, מטרו או תחבורה ציבורית מסוימת.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [
          "e_beyachad_transit"
        ],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_open_spaces_development",
      "topicId": "environment_infrastructure",
      "titleHe": "טבע, שטחים פתוחים ופיתוח עירוני",
      "promptHe": "מה מתועד על הגנת הטבע ועל דפוסי הפיתוח העירוני?",
      "explanationHe": "התחדשות עירונית אינה בהכרח איסור בנייה בשטחים פתוחים; יש לשמור על גבולות הטענה.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [
          "e_beyachad_urban_renewal",
          "e_beyachad_nature"
        ],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [
          "e_pirates_nature"
        ],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_hostage_deal",
      "topicId": "security_foreign_relations",
      "titleHe": "מדיניות להשבת שבויים וחטופים",
      "promptHe": "מה מתועד על כללים מוצעים לעסקאות להשבת שבויים וחטופים?",
      "explanationHe": "הנושא אינו טענה שיש כיום חטופים מסוימים או שכולם הושבו, ואינו קובע את תוכנו של דו״ח שלא נקרא.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [
          "e_yisrael_beitenu_captives"
        ],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_law_of_return_grandchild",
      "topicId": "religion_state",
      "titleHe": "זכאות לעלייה וסעיף הנכד",
      "promptHe": "מה מתועד על הצעות בנוגע לזכאות צאצאים לעלייה?",
      "explanationHe": "עידוד עלייה או סיוע בקליטה אינם כשלעצמם ראיה להצעה על סעיף הנכד.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_internal_security_police",
      "topicId": "institutions_democracy",
      "titleHe": "משטרה וביטחון פנים",
      "promptHe": "מה מתועד על תכניות לשיטור ולמאבק בפשיעה?",
      "explanationHe": "אין לייחס לכל תכנית אכיפה תמיכה במשמר לאומי או בסמכות מעצר מיוחדת.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [
          "e_yashar_police"
        ],
        "yisrael_beitenu": [
          "e_yisrael_beitenu_police"
        ],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [
          "e_amcha_israel_police"
        ],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_agriculture_local_vs_import",
      "topicId": "economy_cost_of_living",
      "titleHe": "תמיכה בחקלאות",
      "promptHe": "מה מתועד על כלי תמיכה בחקלאות המקומית?",
      "explanationHe": "תמיכה ישירה, מכסים ומגבלות יבוא הם כלים שונים; אין להחליף ביניהם.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [
          "e_beyachad_agriculture"
        ],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_us_israel_relations_defense",
      "topicId": "security_foreign_relations",
      "titleHe": "יחסי ישראל וארצות הברית",
      "promptHe": "מה מתועד על מדיניות ביחסים עם ארצות הברית?",
      "explanationHe": "הצהרה על בריתות או תעשייה ביטחונית אינה בהכרח עמדה על הסיוע האמריקאי.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_hightech_taxation_innovation",
      "topicId": "economy_cost_of_living",
      "titleHe": "תמריצים לחדשנות ולהייטק",
      "promptHe": "מה מתועד על כלי מדיניות לחדשנות ולהייטק?",
      "explanationHe": "תכנית כלכלית כללית אינה ראיה להטבת מס ייעודית לחברות הייטק.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_attorney_general_split",
      "topicId": "institutions_democracy",
      "titleHe": "מבנה תפקיד היועץ המשפטי לממשלה",
      "promptHe": "מה מתועד על חלוקת תפקידי הייעוץ המשפטי והתביעה?",
      "explanationHe": "הצעה לשינוי התפקיד אינה ראיה שהוא כבר שונה או שחוות דעת איבדה את מעמדה.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [
          "e_noam_attorney_general"
        ],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_mandatory_civil_service",
      "topicId": "public_services_equality",
      "titleHe": "מסלולי שירות אזרחי",
      "promptHe": "מה מתועד על מסלולי שירות אזרחי ועל תנאי ההשתתפות בהם?",
      "explanationHe": "יש לבדוק מי נכלל בכל הצעה ומהם התנאים; אין לקבוע זכויות אזרחיות על סמך הנחה.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [
          "e_miluimnikim_economic_service"
        ],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [
          "e_yashar_service"
        ],
        "yisrael_beitenu": [
          "e_yisrael_beitenu_service"
        ],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [
          "e_amcha_israel_service"
        ],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_sovereignty",
      "topicId": "security_foreign_relations",
      "titleHe": "מדיניות ריבונות",
      "promptHe": "מה מתועד על עקרונות והצעות להחלת ריבונות?",
      "explanationHe": "יש להבחין בין עיקרון מוצהר לבין הצעה משפטית או מפה מפורטת.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [
          "e_likud_sovereignty"
        ],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_import_customs",
      "topicId": "economy_cost_of_living",
      "titleHe": "יבוא ומכסים",
      "promptHe": "מה מתועד על מדיניות יבוא, תקינה ומכסים?",
      "explanationHe": "עמדה על תחרות אינה לבדה תיעוד להצעה לבטל מכס מסוים.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [
          "e_beyachad_imports"
        ],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [
          "e_yashar_competition"
        ],
        "yisrael_beitenu": [],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_collective_bargaining",
      "topicId": "economy_cost_of_living",
      "titleHe": "התארגנות עובדים",
      "promptHe": "מה מתועד על התארגנות עובדים ועל זכות השביתה?",
      "explanationHe": "אכיפת שכר מינימום אינה בהכרח הצהרה על התארגנות או שביתה.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_judicial_appointments",
      "topicId": "institutions_democracy",
      "titleHe": "מינוי שופטים",
      "promptHe": "מה מתועד על הליך מינוי שופטים?",
      "explanationHe": "מינויי אמון בשירות הציבורי אינם ראיה להצעה על הוועדה לבחירת שופטים.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_coalition_partnership",
      "topicId": "institutions_democracy",
      "titleHe": "כללים לשותפות בקואליציה",
      "promptHe": "מה מתועד על תנאים מוצהרים לשותפות בממשלה?",
      "explanationHe": "אלו הצהרות של רשימה או מרכיב שלה, לא המלצה לבוחר ולא תחזית להרכב ממשלה.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [
          "e_miluimnikim_economic_coalition"
        ],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_religious_administration",
      "topicId": "religion_state",
      "titleHe": "ניהול שירותי הדת",
      "promptHe": "מה מתועד על סמכויות הרבנות ועל ניהול שירותי דת?",
      "explanationHe": "יש להבחין בין שינוי מועצות דתיות, שינוי בלעדיות וביטול גוף.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [
          "e_yisrael_beitenu_religious_services"
        ],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [
          "e_noam_rabbinate"
        ],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_energy_transition",
      "topicId": "environment_infrastructure",
      "titleHe": "מדיניות ייצור האנרגיה",
      "promptHe": "מה מתועד על מעבר בין מקורות אנרגיה ועל אגירה?",
      "explanationHe": "אין להסיק שכל תכנית אקלים כוללת יעד מסוים לאנרגיה מתחדשת.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [
          "e_beyachad_energy"
        ],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_administrative_detention",
      "topicId": "institutions_democracy",
      "titleHe": "סמכויות מעצר מיוחדות",
      "promptHe": "מה מתועד על הצעות לסמכויות מעצר מיוחדות?",
      "explanationHe": "יש לציין במדויק כלפי מי הסמכות מוצעת, ולא להרחיבה לכל אזרח או לכל עבירה.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [
          "e_yisrael_beitenu_detention"
        ],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_transparency",
      "topicId": "institutions_democracy",
      "titleHe": "שקיפות ציבורית",
      "promptHe": "מה מתועד על שקיפות בקבלת החלטות ובשלטון?",
      "explanationHe": "עיקרון מוצהר אינו ראיה שמנגנון שקיפות מסוים כבר פועל.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [
          "e_pirates_transparency"
        ],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_constitution",
      "topicId": "institutions_democracy",
      "titleHe": "חוקה וכללי ממשל",
      "promptHe": "מה מתועד על הצעות לחוקה ולכללי ממשל?",
      "explanationHe": "יש להפריד בין כוונה לקדם חוקה לבין נוסח חוק שאושר.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [
          "e_yisrael_beitenu_constitution"
        ],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    },
    {
      "id": "q_labor_enforcement",
      "topicId": "economy_cost_of_living",
      "titleHe": "אכיפת זכויות עובדים",
      "promptHe": "מה מתועד על אכיפת דיני עבודה ובטיחות?",
      "explanationHe": "זהו נושא נפרד מגובה שכר המינימום ומזכות ההתארגנות.",
      "evidenceByParty": {
        "orot_hashachar": [],
        "ani_veata": [],
        "betach": [],
        "beyachad": [],
        "beyachad_natzliach": [],
        "personal_security": [],
        "brit_olam": [],
        "gan_eden": [],
        "democrats": [],
        "likud": [],
        "miluimnikim_economic": [],
        "pirates": [],
        "haredi_public": [],
        "religious_zionism": [],
        "hakahal": [],
        "joint_list": [
          "e_joint_list_workers"
        ],
        "partnership": [],
        "electoral_fix": [],
        "utj": [],
        "yashar": [],
        "yisrael_beitenu": [],
        "israel_first": [],
        "blue_white": [],
        "biblical_bloc": [],
        "shema": [],
        "tekuma": [],
        "mishpat_tzedek": [],
        "noam": [],
        "seder_hadash": [],
        "otzma_yehudit": [],
        "amcha_israel": [],
        "black_color": [],
        "tzomet_beit_israel": [],
        "kol_hanashim": [],
        "raam": [],
        "shas": [],
        "sharshar": [],
        "achi": []
      }
    }
  ]
};
